%GO Global Output Utility
GT.M 17-SEP-2021 15:07:14
^Football("Arsenal","DomC")
17
^Football("Arsenal","DomL")
13
^Football("Arsenal","DomSC")
16
^Football("Arsenal","DomT")
46
^Football("Arsenal","TotC")
19
^Football("Arsenal","TotL")
13
^Football("Arsenal","TotTot")
48
^Football("Arsenal","UEFAC")
2
^Football("Arsenal","UEFASC")
0
^Football("Arsenal","UEFAT")
2
^Football("Aston_Villa","DomC")
12
^Football("Aston_Villa","DomL")
7
^Football("Aston_Villa","DomSC")
3
^Football("Aston_Villa","DomT")
22
^Football("Aston_Villa","TotC")
14
^Football("Aston_Villa","TotL")
7
^Football("Aston_Villa","TotTot")
25
^Football("Aston_Villa","UEFAC")
2
^Football("Aston_Villa","UEFASC")
1
^Football("Aston_Villa","UEFAT")
3
^Football("Barnsley","DomC")
1
^Football("Barnsley","DomL")
0
^Football("Barnsley","DomSC")
0
^Football("Barnsley","DomT")
1
^Football("Barnsley","TotC")
1
^Football("Barnsley","TotL")
0
^Football("Barnsley","TotTot")
1
^Football("Barnsley","UEFAC")
0
^Football("Barnsley","UEFASC")
0
^Football("Barnsley","UEFAT")
0
^Football("Birmingham_City","DomC")
2
^Football("Birmingham_City","DomL")
0
^Football("Birmingham_City","DomSC")
0
^Football("Birmingham_City","DomT")
2
^Football("Birmingham_City","TotC")
2
^Football("Birmingham_City","TotL")
0
^Football("Birmingham_City","TotTot")
2
^Football("Birmingham_City","UEFAC")
0
^Football("Birmingham_City","UEFASC")
0
^Football("Birmingham_City","UEFAT")
0
^Football("Blackburn_Olympic","DomC")
1
^Football("Blackburn_Olympic","DomL")
0
^Football("Blackburn_Olympic","DomSC")
0
^Football("Blackburn_Olympic","DomT")
1
^Football("Blackburn_Olympic","TotC")
1
^Football("Blackburn_Olympic","TotL")
0
^Football("Blackburn_Olympic","TotTot")
1
^Football("Blackburn_Olympic","UEFAC")
0
^Football("Blackburn_Olympic","UEFASC")
0
^Football("Blackburn_Olympic","UEFAT")
0
^Football("Blackburn_Rovers","DomC")
8
^Football("Blackburn_Rovers","DomL")
3
^Football("Blackburn_Rovers","DomSC")
1
^Football("Blackburn_Rovers","DomT")
12
^Football("Blackburn_Rovers","TotC")
8
^Football("Blackburn_Rovers","TotL")
3
^Football("Blackburn_Rovers","TotTot")
12
^Football("Blackburn_Rovers","UEFAC")
0
^Football("Blackburn_Rovers","UEFASC")
0
^Football("Blackburn_Rovers","UEFAT")
0
^Football("Blackpool","DomC")
1
^Football("Blackpool","DomL")
0
^Football("Blackpool","DomSC")
0
^Football("Blackpool","DomT")
1
^Football("Blackpool","TotC")
1
^Football("Blackpool","TotL")
0
^Football("Blackpool","TotTot")
1
^Football("Blackpool","UEFAC")
0
^Football("Blackpool","UEFASC")
0
^Football("Blackpool","UEFAT")
0
^Football("Bolton_Wanderers","DomC")
4
^Football("Bolton_Wanderers","DomL")
0
^Football("Bolton_Wanderers","DomSC")
1
^Football("Bolton_Wanderers","DomT")
5
^Football("Bolton_Wanderers","TotC")
4
^Football("Bolton_Wanderers","TotL")
0
^Football("Bolton_Wanderers","TotTot")
5
^Football("Bolton_Wanderers","UEFAC")
0
^Football("Bolton_Wanderers","UEFASC")
0
^Football("Bolton_Wanderers","UEFAT")
0
^Football("Bradford_City","DomC")
1
^Football("Bradford_City","DomL")
0
^Football("Bradford_City","DomSC")
0
^Football("Bradford_City","DomT")
1
^Football("Bradford_City","TotC")
1
^Football("Bradford_City","TotL")
0
^Football("Bradford_City","TotTot")
1
^Football("Bradford_City","UEFAC")
0
^Football("Bradford_City","UEFASC")
0
^Football("Bradford_City","UEFAT")
0
^Football("Brighton_&_Hove_Albion","DomC")
0
^Football("Brighton_&_Hove_Albion","DomL")
0
^Football("Brighton_&_Hove_Albion","DomSC")
1
^Football("Brighton_&_Hove_Albion","DomT")
1
^Football("Brighton_&_Hove_Albion","TotC")
0
^Football("Brighton_&_Hove_Albion","TotL")
0
^Football("Brighton_&_Hove_Albion","TotTot")
1
^Football("Brighton_&_Hove_Albion","UEFAC")
0
^Football("Brighton_&_Hove_Albion","UEFASC")
0
^Football("Brighton_&_Hove_Albion","UEFAT")
0
^Football("Burnley","DomC")
1
^Football("Burnley","DomL")
2
^Football("Burnley","DomSC")
2
^Football("Burnley","DomT")
5
^Football("Burnley","TotC")
1
^Football("Burnley","TotL")
2
^Football("Burnley","TotTot")
5
^Football("Burnley","UEFAC")
0
^Football("Burnley","UEFASC")
0
^Football("Burnley","UEFAT")
0
^Football("Bury","DomC")
2
^Football("Bury","DomL")
0
^Football("Bury","DomSC")
0
^Football("Bury","DomT")
2
^Football("Bury","TotC")
2
^Football("Bury","TotL")
0
^Football("Bury","TotTot")
2
^Football("Bury","UEFAC")
0
^Football("Bury","UEFASC")
0
^Football("Bury","UEFAT")
0
^Football("Cardiff_City","DomC")
1
^Football("Cardiff_City","DomL")
0
^Football("Cardiff_City","DomSC")
1
^Football("Cardiff_City","DomT")
2
^Football("Cardiff_City","TotC")
1
^Football("Cardiff_City","TotL")
0
^Football("Cardiff_City","TotTot")
2
^Football("Cardiff_City","UEFAC")
0
^Football("Cardiff_City","UEFASC")
0
^Football("Cardiff_City","UEFAT")
0
^Football("Charlton_Athletic","DomC")
1
^Football("Charlton_Athletic","DomL")
0
^Football("Charlton_Athletic","DomSC")
0
^Football("Charlton_Athletic","DomT")
1
^Football("Charlton_Athletic","TotC")
1
^Football("Charlton_Athletic","TotL")
0
^Football("Charlton_Athletic","TotTot")
1
^Football("Charlton_Athletic","UEFAC")
0
^Football("Charlton_Athletic","UEFASC")
0
^Football("Charlton_Athletic","UEFAT")
0
^Football("Chelsea","DomC")
15
^Football("Chelsea","DomL")
6
^Football("Chelsea","DomSC")
4
^Football("Chelsea","DomT")
25
^Football("Chelsea","TotC")
21
^Football("Chelsea","TotL")
6
^Football("Chelsea","TotTot")
33
^Football("Chelsea","UEFAC")
6
^Football("Chelsea","UEFASC")
2
^Football("Chelsea","UEFAT")
8
^Football("Clapham_Rovers","DomC")
1
^Football("Clapham_Rovers","DomL")
0
^Football("Clapham_Rovers","DomSC")
0
^Football("Clapham_Rovers","DomT")
1
^Football("Clapham_Rovers","TotC")
1
^Football("Clapham_Rovers","TotL")
0
^Football("Clapham_Rovers","TotTot")
1
^Football("Clapham_Rovers","UEFAC")
0
^Football("Clapham_Rovers","UEFASC")
0
^Football("Clapham_Rovers","UEFAT")
0
^Football("Corinthian","DomC")
0
^Football("Corinthian","DomL")
0
^Football("Corinthian","DomSC")
3
^Football("Corinthian","DomT")
3
^Football("Corinthian","TotC")
0
^Football("Corinthian","TotL")
0
^Football("Corinthian","TotTot")
3
^Football("Corinthian","UEFAC")
0
^Football("Corinthian","UEFASC")
0
^Football("Corinthian","UEFAT")
0
^Football("Coventry_City","DomC")
1
^Football("Coventry_City","DomL")
0
^Football("Coventry_City","DomSC")
0
^Football("Coventry_City","DomT")
1
^Football("Coventry_City","TotC")
1
^Football("Coventry_City","TotL")
0
^Football("Coventry_City","TotTot")
1
^Football("Coventry_City","UEFAC")
0
^Football("Coventry_City","UEFASC")
0
^Football("Coventry_City","UEFAT")
0
^Football("Crystal_Palace","DomC")
1
^Football("Crystal_Palace","DomL")
0
^Football("Crystal_Palace","DomSC")
0
^Football("Crystal_Palace","DomT")
1
^Football("Crystal_Palace","TotC")
1
^Football("Crystal_Palace","TotL")
0
^Football("Crystal_Palace","TotTot")
1
^Football("Crystal_Palace","UEFAC")
0
^Football("Crystal_Palace","UEFASC")
0
^Football("Crystal_Palace","UEFAT")
0
^Football("Derby_County","DomC")
1
^Football("Derby_County","DomL")
2
^Football("Derby_County","DomSC")
1
^Football("Derby_County","DomT")
4
^Football("Derby_County","TotC")
1
^Football("Derby_County","TotL")
2
^Football("Derby_County","TotTot")
4
^Football("Derby_County","UEFAC")
0
^Football("Derby_County","UEFASC")
0
^Football("Derby_County","UEFAT")
0
^Football("Everton","DomC")
5
^Football("Everton","DomL")
9
^Football("Everton","DomSC")
9
^Football("Everton","DomT")
23
^Football("Everton","TotC")
6
^Football("Everton","TotL")
9
^Football("Everton","TotTot")
24
^Football("Everton","UEFAC")
1
^Football("Everton","UEFASC")
0
^Football("Everton","UEFAT")
1
^Football("Huddersfield_Town","DomC")
1
^Football("Huddersfield_Town","DomL")
3
^Football("Huddersfield_Town","DomSC")
1
^Football("Huddersfield_Town","DomT")
5
^Football("Huddersfield_Town","TotC")
1
^Football("Huddersfield_Town","TotL")
3
^Football("Huddersfield_Town","TotTot")
5
^Football("Huddersfield_Town","UEFAC")
0
^Football("Huddersfield_Town","UEFASC")
0
^Football("Huddersfield_Town","UEFAT")
0
^Football("Ipswich_Town","DomC")
1
^Football("Ipswich_Town","DomL")
1
^Football("Ipswich_Town","DomSC")
0
^Football("Ipswich_Town","DomT")
2
^Football("Ipswich_Town","TotC")
2
^Football("Ipswich_Town","TotL")
1
^Football("Ipswich_Town","TotTot")
3
^Football("Ipswich_Town","UEFAC")
1
^Football("Ipswich_Town","UEFASC")
0
^Football("Ipswich_Town","UEFAT")
1
^Football("Leeds_United","DomC")
2
^Football("Leeds_United","DomL")
3
^Football("Leeds_United","DomSC")
2
^Football("Leeds_United","DomT")
7
^Football("Leeds_United","TotC")
4
^Football("Leeds_United","TotL")
3
^Football("Leeds_United","TotTot")
9
^Football("Leeds_United","UEFAC")
2
^Football("Leeds_United","UEFASC")
0
^Football("Leeds_United","UEFAT")
2
^Football("Leicester_City","DomC")
4
^Football("Leicester_City","DomL")
1
^Football("Leicester_City","DomSC")
2
^Football("Leicester_City","DomT")
7
^Football("Leicester_City","TotC")
4
^Football("Leicester_City","TotL")
1
^Football("Leicester_City","TotTot")
7
^Football("Leicester_City","UEFAC")
0
^Football("Leicester_City","UEFASC")
0
^Football("Leicester_City","UEFAT")
0
^Football("Liverpool","DomC")
16
^Football("Liverpool","DomL")
19
^Football("Liverpool","DomSC")
16
^Football("Liverpool","DomT")
51
^Football("Liverpool","TotC")
26
^Football("Liverpool","TotL")
19
^Football("Liverpool","TotTot")
65
^Football("Liverpool","UEFAC")
10
^Football("Liverpool","UEFASC")
4
^Football("Liverpool","UEFAT")
14
^Football("Luton_Town","DomC")
1
^Football("Luton_Town","DomL")
0
^Football("Luton_Town","DomSC")
0
^Football("Luton_Town","DomT")
1
^Football("Luton_Town","TotC")
1
^Football("Luton_Town","TotL")
0
^Football("Luton_Town","TotTot")
1
^Football("Luton_Town","UEFAC")
0
^Football("Luton_Town","UEFASC")
0
^Football("Luton_Town","UEFAT")
0
^Football("Manchester_City","DomC")
14
^Football("Manchester_City","DomL")
7
^Football("Manchester_City","DomSC")
6
^Football("Manchester_City","DomT")
27
^Football("Manchester_City","TotC")
15
^Football("Manchester_City","TotL")
7
^Football("Manchester_City","TotTot")
28
^Football("Manchester_City","UEFAC")
1
^Football("Manchester_City","UEFASC")
0
^Football("Manchester_City","UEFAT")
1
^Football("Manchester_United","DomC")
17
^Football("Manchester_United","DomL")
20
^Football("Manchester_United","DomSC")
21
^Football("Manchester_United","DomT")
58
^Football("Manchester_United","TotC")
23
^Football("Manchester_United","TotL")
20
^Football("Manchester_United","TotTot")
66
^Football("Manchester_United","UEFAC")
6
^Football("Manchester_United","UEFASC")
2
^Football("Manchester_United","UEFAT")
8
^Football("Middlesbrough","DomC")
1
^Football("Middlesbrough","DomL")
0
^Football("Middlesbrough","DomSC")
0
^Football("Middlesbrough","DomT")
1
^Football("Middlesbrough","TotC")
1
^Football("Middlesbrough","TotL")
0
^Football("Middlesbrough","TotTot")
1
^Football("Middlesbrough","UEFAC")
0
^Football("Middlesbrough","UEFASC")
0
^Football("Middlesbrough","UEFAT")
0
^Football("Newcastle_United","DomC")
6
^Football("Newcastle_United","DomL")
4
^Football("Newcastle_United","DomSC")
2
^Football("Newcastle_United","DomT")
12
^Football("Newcastle_United","TotC")
8
^Football("Newcastle_United","TotL")
4
^Football("Newcastle_United","TotTot")
14
^Football("Newcastle_United","UEFAC")
2
^Football("Newcastle_United","UEFASC")
0
^Football("Newcastle_United","UEFAT")
2
^Football("Norwich_City","DomC")
2
^Football("Norwich_City","DomL")
0
^Football("Norwich_City","DomSC")
0
^Football("Norwich_City","DomT")
2
^Football("Norwich_City","TotC")
2
^Football("Norwich_City","TotL")
0
^Football("Norwich_City","TotTot")
2
^Football("Norwich_City","UEFAC")
0
^Football("Norwich_City","UEFASC")
0
^Football("Norwich_City","UEFAT")
0
^Football("Nottingham_Forest","DomC")
8
^Football("Nottingham_Forest","DomL")
1
^Football("Nottingham_Forest","DomSC")
1
^Football("Nottingham_Forest","DomT")
10
^Football("Nottingham_Forest","TotC")
10
^Football("Nottingham_Forest","TotL")
1
^Football("Nottingham_Forest","TotTot")
13
^Football("Nottingham_Forest","UEFAC")
2
^Football("Nottingham_Forest","UEFASC")
1
^Football("Nottingham_Forest","UEFAT")
3
^Football("Notts_County","DomC")
1
^Football("Notts_County","DomL")
0
^Football("Notts_County","DomSC")
0
^Football("Notts_County","DomT")
1
^Football("Notts_County","TotC")
1
^Football("Notts_County","TotL")
0
^Football("Notts_County","TotTot")
1
^Football("Notts_County","UEFAC")
0
^Football("Notts_County","UEFASC")
0
^Football("Notts_County","UEFAT")
0
^Football("Old_Carthusians","DomC")
1
^Football("Old_Carthusians","DomL")
0
^Football("Old_Carthusians","DomSC")
0
^Football("Old_Carthusians","DomT")
1
^Football("Old_Carthusians","TotC")
1
^Football("Old_Carthusians","TotL")
0
^Football("Old_Carthusians","TotTot")
1
^Football("Old_Carthusians","UEFAC")
0
^Football("Old_Carthusians","UEFASC")
0
^Football("Old_Carthusians","UEFAT")
0
^Football("Old_Etonians","DomC")
2
^Football("Old_Etonians","DomL")
0
^Football("Old_Etonians","DomSC")
0
^Football("Old_Etonians","DomT")
2
^Football("Old_Etonians","TotC")
2
^Football("Old_Etonians","TotL")
0
^Football("Old_Etonians","TotTot")
2
^Football("Old_Etonians","UEFAC")
0
^Football("Old_Etonians","UEFASC")
0
^Football("Old_Etonians","UEFAT")
0
^Football("Oxford_United","DomC")
1
^Football("Oxford_United","DomL")
0
^Football("Oxford_United","DomSC")
0
^Football("Oxford_United","DomT")
1
^Football("Oxford_United","TotC")
1
^Football("Oxford_United","TotL")
0
^Football("Oxford_United","TotTot")
1
^Football("Oxford_United","UEFAC")
0
^Football("Oxford_United","UEFASC")
0
^Football("Oxford_United","UEFAT")
0
^Football("Oxford_University","DomC")
1
^Football("Oxford_University","DomL")
0
^Football("Oxford_University","DomSC")
0
^Football("Oxford_University","DomT")
1
^Football("Oxford_University","TotC")
1
^Football("Oxford_University","TotL")
0
^Football("Oxford_University","TotTot")
1
^Football("Oxford_University","UEFAC")
0
^Football("Oxford_University","UEFASC")
0
^Football("Oxford_University","UEFAT")
0
^Football("Portsmouth","DomC")
2
^Football("Portsmouth","DomL")
2
^Football("Portsmouth","DomSC")
1
^Football("Portsmouth","DomT")
5
^Football("Portsmouth","TotC")
2
^Football("Portsmouth","TotL")
2
^Football("Portsmouth","TotTot")
5
^Football("Portsmouth","UEFAC")
0
^Football("Portsmouth","UEFASC")
0
^Football("Portsmouth","UEFAT")
0
^Football("Preston_North_End","DomC")
2
^Football("Preston_North_End","DomL")
2
^Football("Preston_North_End","DomSC")
0
^Football("Preston_North_End","DomT")
4
^Football("Preston_North_End","TotC")
2
^Football("Preston_North_End","TotL")
2
^Football("Preston_North_End","TotTot")
4
^Football("Preston_North_End","UEFAC")
0
^Football("Preston_North_End","UEFASC")
0
^Football("Preston_North_End","UEFAT")
0
^Football("Queens_Park","DomC")
0
^Football("Queens_Park","DomL")
0
^Football("Queens_Park","DomSC")
1
^Football("Queens_Park","DomT")
1
^Football("Queens_Park","TotC")
0
^Football("Queens_Park","TotL")
0
^Football("Queens_Park","TotTot")
1
^Football("Queens_Park","UEFAC")
0
^Football("Queens_Park","UEFASC")
0
^Football("Queens_Park","UEFAT")
0
^Football("Queens_Park_Rangers","DomC")
1
^Football("Queens_Park_Rangers","DomL")
0
^Football("Queens_Park_Rangers","DomSC")
0
^Football("Queens_Park_Rangers","DomT")
1
^Football("Queens_Park_Rangers","TotC")
1
^Football("Queens_Park_Rangers","TotL")
0
^Football("Queens_Park_Rangers","TotTot")
1
^Football("Queens_Park_Rangers","UEFAC")
0
^Football("Queens_Park_Rangers","UEFASC")
0
^Football("Queens_Park_Rangers","UEFAT")
0
^Football("Reading","DomC")
1
^Football("Reading","DomL")
0
^Football("Reading","DomSC")
0
^Football("Reading","DomT")
1
^Football("Reading","TotC")
1
^Football("Reading","TotL")
0
^Football("Reading","TotTot")
1
^Football("Reading","UEFAC")
0
^Football("Reading","UEFASC")
0
^Football("Reading","UEFAT")
0
^Football("Royal_Engineers","DomC")
1
^Football("Royal_Engineers","DomL")
0
^Football("Royal_Engineers","DomSC")
0
^Football("Royal_Engineers","DomT")
1
^Football("Royal_Engineers","TotC")
1
^Football("Royal_Engineers","TotL")
0
^Football("Royal_Engineers","TotTot")
1
^Football("Royal_Engineers","UEFAC")
0
^Football("Royal_Engineers","UEFASC")
0
^Football("Royal_Engineers","UEFAT")
0
^Football("Sheffield_United","DomC")
4
^Football("Sheffield_United","DomL")
1
^Football("Sheffield_United","DomSC")
1
^Football("Sheffield_United","DomT")
6
^Football("Sheffield_United","TotC")
4
^Football("Sheffield_United","TotL")
1
^Football("Sheffield_United","TotTot")
6
^Football("Sheffield_United","UEFAC")
0
^Football("Sheffield_United","UEFASC")
0
^Football("Sheffield_United","UEFAT")
0
^Football("Sheffield_Wednesday","DomC")
4
^Football("Sheffield_Wednesday","DomL")
4
^Football("Sheffield_Wednesday","DomSC")
2
^Football("Sheffield_Wednesday","DomT")
10
^Football("Sheffield_Wednesday","TotC")
4
^Football("Sheffield_Wednesday","TotL")
4
^Football("Sheffield_Wednesday","TotTot")
10
^Football("Sheffield_Wednesday","UEFAC")
0
^Football("Sheffield_Wednesday","UEFASC")
0
^Football("Sheffield_Wednesday","UEFAT")
0
^Football("Southampton","DomC")
1
^Football("Southampton","DomL")
0
^Football("Southampton","DomSC")
0
^Football("Southampton","DomT")
1
^Football("Southampton","TotC")
1
^Football("Southampton","TotL")
0
^Football("Southampton","TotTot")
1
^Football("Southampton","UEFAC")
0
^Football("Southampton","UEFASC")
0
^Football("Southampton","UEFAT")
0
^Football("Stoke_City","DomC")
1
^Football("Stoke_City","DomL")
0
^Football("Stoke_City","DomSC")
0
^Football("Stoke_City","DomT")
1
^Football("Stoke_City","TotC")
1
^Football("Stoke_City","TotL")
0
^Football("Stoke_City","TotTot")
1
^Football("Stoke_City","UEFAC")
0
^Football("Stoke_City","UEFASC")
0
^Football("Stoke_City","UEFAT")
0
^Football("Sunderland","DomC")
2
^Football("Sunderland","DomL")
6
^Football("Sunderland","DomSC")
2
^Football("Sunderland","DomT")
10
^Football("Sunderland","TotC")
2
^Football("Sunderland","TotL")
6
^Football("Sunderland","TotTot")
10
^Football("Sunderland","UEFAC")
0
^Football("Sunderland","UEFASC")
0
^Football("Sunderland","UEFAT")
0
^Football("Swansea_City","DomC")
1
^Football("Swansea_City","DomL")
0
^Football("Swansea_City","DomSC")
0
^Football("Swansea_City","DomT")
1
^Football("Swansea_City","TotC")
1
^Football("Swansea_City","TotL")
0
^Football("Swansea_City","TotTot")
1
^Football("Swansea_City","UEFAC")
0
^Football("Swansea_City","UEFASC")
0
^Football("Swansea_City","UEFAT")
0
^Football("Swindon_Town","DomC")
1
^Football("Swindon_Town","DomL")
0
^Football("Swindon_Town","DomSC")
1
^Football("Swindon_Town","DomT")
2
^Football("Swindon_Town","TotC")
1
^Football("Swindon_Town","TotL")
0
^Football("Swindon_Town","TotTot")
2
^Football("Swindon_Town","UEFAC")
0
^Football("Swindon_Town","UEFASC")
0
^Football("Swindon_Town","UEFAT")
0
^Football("Tottenham Hotspur","DomC")
12
^Football("Tottenham Hotspur","DomL")
2
^Football("Tottenham Hotspur","DomSC")
9
^Football("Tottenham Hotspur","DomT")
23
^Football("Tottenham Hotspur","TotC")
15
^Football("Tottenham Hotspur","TotL")
2
^Football("Tottenham Hotspur","TotTot")
26
^Football("Tottenham Hotspur","UEFAC")
3
^Football("Tottenham Hotspur","UEFASC")
0
^Football("Tottenham Hotspur","UEFAT")
3
^Football("Wanderers","DomC")
5
^Football("Wanderers","DomL")
0
^Football("Wanderers","DomSC")
0
^Football("Wanderers","DomT")
5
^Football("Wanderers","TotC")
5
^Football("Wanderers","TotL")
0
^Football("Wanderers","TotTot")
5
^Football("Wanderers","UEFAC")
0
^Football("Wanderers","UEFASC")
0
^Football("Wanderers","UEFAT")
0
^Football("West_Bromwich_Albion","DomC")
6
^Football("West_Bromwich_Albion","DomL")
1
^Football("West_Bromwich_Albion","DomSC")
2
^Football("West_Bromwich_Albion","DomT")
9
^Football("West_Bromwich_Albion","TotC")
6
^Football("West_Bromwich_Albion","TotL")
1
^Football("West_Bromwich_Albion","TotTot")
9
^Football("West_Bromwich_Albion","UEFAC")
0
^Football("West_Bromwich_Albion","UEFASC")
0
^Football("West_Bromwich_Albion","UEFAT")
0
^Football("West_Ham_United","DomC")
3
^Football("West_Ham_United","DomL")
0
^Football("West_Ham_United","DomSC")
1
^Football("West_Ham_United","DomT")
4
^Football("West_Ham_United","TotC")
5
^Football("West_Ham_United","TotL")
0
^Football("West_Ham_United","TotTot")
6
^Football("West_Ham_United","UEFAC")
2
^Football("West_Ham_United","UEFASC")
0
^Football("West_Ham_United","UEFAT")
2
^Football("Wigan_Athletic","DomC")
1
^Football("Wigan_Athletic","DomL")
0
^Football("Wigan_Athletic","DomSC")
0
^Football("Wigan_Athletic","DomT")
1
^Football("Wigan_Athletic","TotC")
1
^Football("Wigan_Athletic","TotL")
0
^Football("Wigan_Athletic","TotTot")
1
^Football("Wigan_Athletic","UEFAC")
0
^Football("Wigan_Athletic","UEFASC")
0
^Football("Wigan_Athletic","UEFAT")
0
^Football("Wimbledon","DomC")
1
^Football("Wimbledon","DomL")
0
^Football("Wimbledon","DomSC")
0
^Football("Wimbledon","DomT")
1
^Football("Wimbledon","TotC")
1
^Football("Wimbledon","TotL")
0
^Football("Wimbledon","TotTot")
1
^Football("Wimbledon","UEFAC")
0
^Football("Wimbledon","UEFASC")
0
^Football("Wimbledon","UEFAT")
0
^Football("Wolverhampton_Wanderers","DomC")
6
^Football("Wolverhampton_Wanderers","DomL")
3
^Football("Wolverhampton_Wanderers","DomSC")
4
^Football("Wolverhampton_Wanderers","DomT")
13
^Football("Wolverhampton_Wanderers","TotC")
6
^Football("Wolverhampton_Wanderers","TotL")
3
^Football("Wolverhampton_Wanderers","TotTot")
13
^Football("Wolverhampton_Wanderers","UEFAC")
0
^Football("Wolverhampton_Wanderers","UEFASC")
0
^Football("Wolverhampton_Wanderers","UEFAT")
0


