apiVersion: apps/v1
kind: Deployment
metadata:
  name: yottamgweb-deploy
  labels:
    app: yottamgweb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yottamgweb
  template:
    metadata:
      labels:
        app: yottamgweb
    spec:
      containers:
      - name: yottamgweb
        image: docker.io/ramb0/yotta-mgweb:latest
        command: ["/bin/bash"]
        args: ["-c","/home/git/YottaDB-Demo/Kubernetes/mgwebentry/entrypoint.sh"]
        env:
        - name: glbviewport
          value: "8001"
        - name: glbviewadd
          value: "localhost"
        - name: ydb_gbldir
          value: "/opt/yottadb/yottadb.gld"
        ports:
        - containerPort: 8080
        - containerPort: 8001
        livenessProbe:
          httpGet:
           path: /
           port: 8080
          initialDelaySeconds: 10
          periodSeconds: 3
        volumeMounts:
        - mountPath: "/home/project"
          name: demovol
        - mountPath: "/opt/yottadb"
          name: yottavol
        - mountPath: "/home/git"
          name: gitvol
      volumes:
      - name: demovol
        persistentVolumeClaim:
          claimName: demo-pvc
      - name: yottavol
        persistentVolumeClaim:
          claimName: yotta-pvc
      - name: gitvol
        persistentVolumeClaim:
          claimName: git-pvc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ide-deployment
  labels:
    app: ide
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ide
  template:
    metadata:
      labels:
        app: ide
    spec:
      containers:
      - name: ide
        image: docker.io/ramb0/theia-mumps:latest
        command: ["/bin/bash"]
        args: ["-c","/home/git/YottaDB-Demo/Kubernetes/ideentry/entrypoint.sh"]
        ports:
        - containerPort: 3000
        livenessProbe:
          httpGet:
           path: /
           port: 3000
          initialDelaySeconds: 10
          periodSeconds: 3
        volumeMounts:
        - mountPath: "/home/project"
          name: demovol
        - mountPath: "/home/git"
          name: gitvol
      volumes:
      - name: demovol
        persistentVolumeClaim:
          claimName: demo-pvc
      - name: gitvol
        persistentVolumeClaim:
          claimName: git-pvc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: metabase-deployment
  labels:
    app: metabase
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metabase
  template:
    metadata:
      labels:
        app: metabase
    spec:
      containers:
      - name: metabase
        image: docker.io/huksley/metabase
        command: ["/bin/bash"]
        args: ["-c","/home/git/YottaDB-Demo/Kubernetes/metaentry/entrypoint.sh"]
        env:
        - name: MB_DB_FILE
          value: "/home/metabase/metabase.db"
        ports:
        - containerPort: 3000
        livenessProbe:
          httpGet:
           path: /
           port: 3000
          initialDelaySeconds: 10
          periodSeconds: 3

        volumeMounts:
        - mountPath: "/home/project"
          name: demovol
        - mountPath: "/home/git"
          name: gitvol
      volumes:
      - name: demovol
        persistentVolumeClaim:
          claimName: demo-pvc
      - name: gitvol
        persistentVolumeClaim:
          claimName: git-pvc

