apiVersion: batch/v1
kind: Job
metadata:
  name: init-job
spec:
  template:
    spec:
      containers:
      - name: init-job
        image: docker.io/ramb0/yotta-mgweb:latest
        command: ['/bin/bash', '-c', "cd /home/git && if test -d /home/git/YottaDB-Demo;then rm -Rf /home/git/YottaDB-Demo;fi && git clone -b git https://github.com/RamSailopal/YottaDB-Demo.git && /home/git/YottaDB-Demo/Kubernetes/mgwebentry/initentry.sh"]
        volumeMounts:
        - mountPath: "/home/git"
          name: gitvol
        - mountPath: "/opt/yottadb"
          name: yottavol
      volumes:
      - name: gitvol
        persistentVolumeClaim:
          claimName: git-pvc
      - name: yottavol
        persistentVolumeClaim:
          claimName: yotta-pvc
      restartPolicy: Never
  backoffLimit: 4
