apiVersion: batch/v1
kind: Job
metadata:
  name: yottamgweb-init
spec:
  template:
    spec:
      containers:
      - name: yottamgweb-init
        image: docker.io/ramb0/yotta-mgweb:latest
        command: ["/bin/bash"]
        args: ["-c","/home/entrypoint/entrypoint.sh"]
        env:
        - name: glbviewport
          value: "8001"
        - name: glbviewadd
          value: "localhost"
        - name: ydb_gbldir
          value: "/opt/yottadb/yottadb.gld"
        ports:
        - containerPort: 8080
        - containerPort: 8001
        volumeMounts:
        - mountPath: "/home/project"
          name: demovol
        - mountPath: "/opt/yottadb"
          name: yottavol
        - mountPath: "/root/.ssh"
          name: ssh
        - mountPath: "/etc/lsyncd.conf"
          name: lsync
        - mountPath: "/home/footie"
          name: footie
        - mountPath: "/home/entrypoint"
          name: entrypoint
        - mountPath: "/opt/mgweb/mapped"
          name: mgweb
      volumes:
      - name: demovol
        persistentVolumeClaim:
          claimName: demo-pvc
      - name: yottavol
        persistentVolumeClaim:
          claimName: yotta-pvc
      - name: ssh
        hostPath:
          path: /usr/local/YottaDB-Demo/.ssh
      - name: lsync
        hostPath:
          path: /usr/local/YottaDB-Demo/lsyncd/lysncd.conf
      - name: footie
        hostPath:
          path: /usr/local/YottaDB-Demo/EnglishFootball
      - name: entrypoint
        hostPath:
          path: /usr/local/YottaDB-Demo/Kubernetes/initentry
      - name: mgweb
        hostPath:
          path: /usr/local/YottaDB-Demo/mapped
      restartPolicy: Never
  backoffLimit: 4    
