---
apiVersion: v1
kind: Service
metadata:
  name: yottamgweb
spec:
  selector:
    app: yottamgweb
  ports:
    - port: 8080
      targetPort: 8080
  externalIPs:
    - $IPADD
---
apiVersion: v1
kind: Service
metadata:
  name: yotta-global
spec:
  selector:
    app: yottaglobal
  ports:
    - port: 8001
      targetPort: 8001
  externalIPs:
    - $IPADD
---
apiVersion: v1
kind: Service
metadata:
  name: metabase
spec:
  selector:
    app: metabase
  ports:
    - port: 3000
      targetPort: 3000
  externalIPs:
    - $IPADD
---
apiVersion: v1
kind: Service
metadata:
  name: ide
spec:
  selector:
    app: ide
  ports:
    - port: 3002
      targetPort: 3000
  externalIPs:
    - $IPADD
